
SRCDIR = $(ROOT)/src/semesh/
BIN = $(ROOT)/bin/semesh

CPPFILES := $(shell echo $(SRCDIR)*.cpp)
OBJFILES = $(CPPFILES:.cpp=.o)
OBJECTS = $(notdir $(OBJFILES))

$(BIN): $(OBJECTS)
	$(CC) $(OBJECTS) $(LFLAGS) -o $(BIN)

%.o: $(SRCDIR)%.cpp
	$(CC) -c $(CFLAGS) $< -o $@

