
SRCDIR = $(ROOT)/src/se/
LIB = $(ROOT)/lib/libse.a

CPPFILES := $(shell echo $(SRCDIR)*.cpp)
OBJFILES = $(CPPFILES:.cpp=.o)
OBJECTS = $(notdir $(OBJFILES))

$(LIB): $(OBJECTS)
	ar -r $(LIB) $(OBJECTS)

%.o: $(SRCDIR)%.cpp
	$(CC) -c $(CFLAGS) $< -o $@

