/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set ts=8 sts=2 et sw=2 tw=80: */
/* This file was auto-generated from e:/0ad/libraries/source/spidermonkey/mozjs-78.6.0/mozglue/dllservices/WindowsDllBlocklistDefs.in by gen_dll_blocklist_data.py.  */

#ifndef mozilla_WindowsDllBlocklistLegacyDefs_h
#define mozilla_WindowsDllBlocklistLegacyDefs_h

#include "mozilla/WindowsDllBlocklistCommon.h"

DLL_BLOCKLIST_DEFINITIONS_BEGIN

  DLL_BLOCKLIST_ENTRY("accelerator.dll", MAKE_VERSION(3, 2, 1, 6))
  DLL_BLOCKLIST_ENTRY("activedetect32.dll", DllBlockInfo::UNVERSIONED)
  DLL_BLOCKLIST_ENTRY("activedetect64.dll", DllBlockInfo::UNVERSIONED)
  DLL_BLOCKLIST_ENTRY("atkdx11disp.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("avgrsstx.dll", MAKE_VERSION(8, 5, 0, 401))
  DLL_BLOCKLIST_ENTRY("babyfox.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("banksafe64.dll", MAKE_VERSION(1, 2, 15299, 65535))
  DLL_BLOCKLIST_ENTRY("beid35cardlayer.dll", MAKE_VERSION(3, 5, 6, 6968))
  DLL_BLOCKLIST_ENTRY("bitguard.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("bletokencredentialprovider.dll", MAKE_VERSION(2, 1, 63, 0), DllBlockInfo::BROWSER_PROCESS_ONLY)
  DLL_BLOCKLIST_ENTRY("calc.dll", MAKE_VERSION(1, 0, 0, 1))
  DLL_BLOCKLIST_ENTRY("database.dll", MAKE_VERSION(27, 3, 0, 59), DllBlockInfo::BROWSER_PROCESS_ONLY)
  DLL_BLOCKLIST_ENTRY("dbroverlayiconbackuped.dll", MAKE_VERSION(1, 8, 0, 9))
  DLL_BLOCKLIST_ENTRY("dbroverlayiconnotbackuped.dll", MAKE_VERSION(1, 8, 0, 9))
  DLL_BLOCKLIST_ENTRY("dgapi.dll", MAKE_VERSION(7, 5, 0, 65535), DllBlockInfo::REDIRECT_TO_NOOP_ENTRYPOINT)
  DLL_BLOCKLIST_ENTRY("dgapi64.dll", MAKE_VERSION(7, 5, 0, 65535), DllBlockInfo::REDIRECT_TO_NOOP_ENTRYPOINT)
  DLL_BLOCKLIST_ENTRY("dtwxsvc.dll", 0x53153234U, DllBlockInfo::USE_TIMESTAMP)
  DLL_BLOCKLIST_ENTRY("eoppmonitor.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("fgjk4wvb.dll", MAKE_VERSION(8, 8, 8, 8))
  DLL_BLOCKLIST_ENTRY("gdkbfltdll64.dll", MAKE_VERSION(1, 0, 14141, 240))
  DLL_BLOCKLIST_ENTRY("googledesktopnetwork3.dll", DllBlockInfo::UNVERSIONED)
  DLL_BLOCKLIST_ENTRY("grabdll.dll", MAKE_VERSION(2, 6, 1, 0))
  DLL_BLOCKLIST_ENTRY("grabkernel.dll", MAKE_VERSION(1, 0, 0, 1))
  DLL_BLOCKLIST_ENTRY("guard64.dll", MAKE_VERSION(5, 12, 59641, 2599))
  DLL_BLOCKLIST_ENTRY("hncshellext64.dll", MAKE_VERSION(1, 0, 0, 3), DllBlockInfo::BROWSER_PROCESS_ONLY)
  DLL_BLOCKLIST_ENTRY("hook.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("idmcchandler5.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("idmcchandler5_64.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("idmcchandler7.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("idmcchandler7_64.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("iseguard32.dll", MAKE_VERSION(1, 6, 13835, 184))
  DLL_BLOCKLIST_ENTRY("iseguard64.dll", MAKE_VERSION(1, 6, 13835, 184))
  DLL_BLOCKLIST_ENTRY("k7pswsen.dll", MAKE_VERSION(15, 2, 2, 95))
  DLL_BLOCKLIST_ENTRY("klsihk64.dll", MAKE_VERSION(14, 0, 456, 65535), DllBlockInfo::BLOCK_WIN8_AND_OLDER)
  DLL_BLOCKLIST_ENTRY("libinject.dll", DllBlockInfo::UNVERSIONED)
  DLL_BLOCKLIST_ENTRY("libinject2.dll", 0x537DDC93U, DllBlockInfo::USE_TIMESTAMP)
  DLL_BLOCKLIST_ENTRY("libredir2.dll", 0x5385B7EDU, DllBlockInfo::USE_TIMESTAMP)
  DLL_BLOCKLIST_ENTRY("mfflac.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("nahimic2devprops.dll", MAKE_VERSION(2, 5, 19, 65535))
  DLL_BLOCKLIST_ENTRY("nahimic2osd.dll", MAKE_VERSION(2, 5, 19, 65535))
  DLL_BLOCKLIST_ENTRY("nahimicmsidevprops.dll", DllBlockInfo::UNVERSIONED)
  DLL_BLOCKLIST_ENTRY("nahimicmsiosd.dll", DllBlockInfo::UNVERSIONED)
  DLL_BLOCKLIST_ENTRY("nahimicvrdevprops.dll", DllBlockInfo::UNVERSIONED)
  DLL_BLOCKLIST_ENTRY("nhasusstrixdevprops.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("nhasusstrixosd.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("nlsp.dll", MAKE_VERSION(6, 23, 2012, 19))
  DLL_BLOCKLIST_ENTRY("npffaddon.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("nprndlffbrowserrecordext.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("nprpffbrowserrecordext.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("nviewh64.dll", MAKE_VERSION(6, 14, 10, 14847))
  DLL_BLOCKLIST_ENTRY("nzbrcom.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("oly.dll", MAKE_VERSION(1, 1, 3, 19920), DllBlockInfo::BROWSER_PROCESS_ONLY)
  DLL_BLOCKLIST_ENTRY("oly64.dll", MAKE_VERSION(1, 1, 3, 19920), DllBlockInfo::BROWSER_PROCESS_ONLY)
  DLL_BLOCKLIST_ENTRY("onepin-opensc-pkcs11.dll", MAKE_VERSION(0, 19, 0, 448))
  DLL_BLOCKLIST_ENTRY("opls.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("opls64.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("opnx.dll", MAKE_VERSION(1, 3, 334, 9))
  DLL_BLOCKLIST_ENTRY("pdzipmenu32.dll", MAKE_VERSION(1, 4, 4, 20103), DllBlockInfo::BROWSER_PROCESS_ONLY)
  DLL_BLOCKLIST_ENTRY("pdzipmenu64.dll", MAKE_VERSION(1, 4, 4, 20103), DllBlockInfo::BROWSER_PROCESS_ONLY)
  DLL_BLOCKLIST_ENTRY("pghook.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("pmls.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("pmls64.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("pmnx.dll", MAKE_VERSION(1, 3, 334, 9))
  DLL_BLOCKLIST_ENTRY("prls.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("prls64.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("prnx.dll", MAKE_VERSION(1, 3, 334, 9))
  DLL_BLOCKLIST_ENTRY("psicon.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("radhslib.dll", DllBlockInfo::UNVERSIONED)
  DLL_BLOCKLIST_ENTRY("rdolib.dll", MAKE_VERSION(6, 0, 88, 4))
  DLL_BLOCKLIST_ENTRY("rf-firefox-22.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("rf-firefox-40.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("rf-firefox.dll", MAKE_VERSION(7, 6, 1, 0))
  DLL_BLOCKLIST_ENTRY("rlls.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("rlls64.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("rlnx.dll", MAKE_VERSION(1, 3, 334, 9))
  DLL_BLOCKLIST_ENTRY("rlxf.dll", MAKE_VERSION(1, 2, 323, 1))
  DLL_BLOCKLIST_ENTRY("rndlmainbrowserrecordplugin.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("rndlnpshimswf.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("roboform.dll", MAKE_VERSION(7, 6, 1, 0))
  DLL_BLOCKLIST_ENTRY("safemon64.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("smci32.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("smci64.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("sprotector.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("spvc32.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("ss2devprops.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("ss2osd.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("sxwmon.dll", DllBlockInfo::ALL_VERSIONS)
  DLL_BLOCKLIST_ENTRY("sxwmon64.dll", DllBlockInfo::ALL_VERSIONS)
#if defined(ENABLE_TESTS)
  DLL_BLOCKLIST_ENTRY("testdllblocklist_allowbyversion.dll", MAKE_VERSION(5, 5, 5, 5))
#endif  // defined(ENABLE_TESTS)
#if defined(ENABLE_TESTS)
  DLL_BLOCKLIST_ENTRY("testdllblocklist_matchbyname.dll", DllBlockInfo::ALL_VERSIONS)
#endif  // defined(ENABLE_TESTS)
#if defined(ENABLE_TESTS)
  DLL_BLOCKLIST_ENTRY("testdllblocklist_matchbyversion.dll", MAKE_VERSION(5, 5, 5, 5))
#endif  // defined(ENABLE_TESTS)
#if defined(ENABLE_TESTS)
  DLL_BLOCKLIST_ENTRY("testdllblocklist_noopentrypoint.dll", MAKE_VERSION(5, 5, 5, 5), DllBlockInfo::REDIRECT_TO_NOOP_ENTRYPOINT)
#endif  // defined(ENABLE_TESTS)
  DLL_BLOCKLIST_ENTRY("vksaver.dll", MAKE_VERSION(2, 2, 2, 0))
  DLL_BLOCKLIST_ENTRY("vorbis.acm", MAKE_VERSION(0, 0, 3, 6))
  DLL_BLOCKLIST_ENTRY("vwcsource.ax", MAKE_VERSION(1, 5, 0, 0))
  DLL_BLOCKLIST_ENTRY("wbload.dll", DllBlockInfo::ALL_VERSIONS, DllBlockInfo::CHILD_PROCESSES_ONLY)
  DLL_BLOCKLIST_ENTRY("windowsapihookdll32.dll", DllBlockInfo::UNVERSIONED)
  DLL_BLOCKLIST_ENTRY("windowsapihookdll64.dll", DllBlockInfo::UNVERSIONED)
  DLL_BLOCKLIST_ENTRY("ycwebcamerasource.ax", MAKE_VERSION(2, 0, 0, 1611))

DLL_BLOCKLIST_DEFINITIONS_END

#endif  // mozilla_WindowsDllBlocklistLegacyDefs_h

